[[redirects]]
	from = "/codeofconduct"
	to = "/assets/dh18_code_of_conduct.pdf"
	status = 302

[[redirects]]
	from = "/sponsorshipdeck"
	to = "https://drive.google.com/file/d/1-XTLcm9eFmUsyVWDA9PQOrBvniFXPFmr/view"
	status = 302

[[redirects]]
	from = "/visaletter"
	to = "https://ducompsoc.typeform.com/to/Xr4WLQ"
	status = 302

[[redirects]]
	from = "/slack"
	to = "https://join.slack.com/t/durhack2020/shared_invite/zt-itglx4zo-lzZz73KSwGzk534oHVmNKw"
	status = 302

[[redirects]]
	from = "/travel"
	to = "https://ducompsoc.typeform.com/to/Rjz1Js"
	status = 302

[[redirects]]
	from = "/devpost"
	to = "https://durhack2022.devpost.com"
	status = 302

[[redirects]]
	from = "/tables"
	to = "https://durhack2019.devpost.com/tables"
	status = 302

[[redirects]]
	from = "/staff_feedback"
	to = "https://ducompsoc.typeform.com/to/HGEsYJ"
	status = 302

[[redirects]]
	from = "/jointheteam"
	to = "https://ducompsoc.typeform.com/to/jgFR9EJp"
	status = 302

[[redirects]]
	from = "/organise"
	to = "https://ducompsoc.typeform.com/to/jgFR9EJp"
	status = 302

[[redirects]]
	from ="/consentform"
	to = "/assets/consent_form.pdf"
	status = 302

[[redirects]]
	from = "/register-du"
	to = "https://ducompsoc.typeform.com/to/lrHtJxcx"
	status = 302

[[redirects]]
	from = "/register-nondu"
	to = "https://ducompsoc.typeform.com/to/KtmC0kLz"
	status = 302

[[redirects]]
	from = "/tickets"
	to = "/#tickets"
	status = 302

[[redirects]]
	from = "/register-interest"
	to = "https://ducompsoc.typeform.com/to/FPPtBxHo"
	status = 302

[[redirects]]
	from = "/preregister"
	to = "https://durhack.com/register"
	status = 302

[[redirects]]
	from = "/volunteer"
	to = "https://ducompsoc.typeform.com/to/E1F8lUpK"
	status = 302

[[redirects]]
	from = "/toolbox"
	to = "/assets/toolbox.pdf"
	status = 302

[[redirects]]
	from = "/zoombackgrounds"
	to = "https://drive.google.com/drive/folders/19w-Smy4ZSAJs1iGWyvEJO2fP66FF482A?usp=sharing"
	status = 302

[[redirects]]
	from = "/hackerguide"
	to = "https://drive.google.com/file/d/1e5B8RYHX12pM1MvHOR8eVB6UaLnVpH03/view?usp=sharing"
	status = 302

[[redirects]]
	from = "/live"
	to = "https://live.durhack.com/"
	status = 302

[[redirects]]
	from = "/discord"
	to = "https://live.durhack.com/"
	status = 302

[[redirects]]
	from = "/stash"
	to = "https://ducompsoc.typeform.com/to/zWTBEURF"
	status = 302

[dev]
	publish = "dist/"
