[[redirects]]
	from = "/codeofconduct"
	to = "/assets/dh18_code_of_conduct.pdf"
	status = 302

[[redirects]]
	from = "/sponsorshipdeck"
	to = "https://drive.google.com/file/d/1-XTLcm9eFmUsyVWDA9PQOrBvniFXPFmr/view"
	status = 302

[[redirects]]
	from = "/visaletter"
	to = "https://ducompsoc.typeform.com/to/Xr4WLQ"
	status = 302

[[redirects]]
	from = "/slack"
	to = "https://join.slack.com/t/durhack2020/shared_invite/zt-itglx4zo-lzZz73KSwGzk534oHVmNKw"
	status = 302

[[redirects]]
	from = "/travel"
	to = "https://ducompsoc.typeform.com/to/Rjz1Js"
	status = 302

[[redirects]]
	from = "/devpost"
	to = "https://durhack-2020.devpost.com"
	status = 302

[[redirects]]
	from = "/tables"
	to = "https://durhack2019.devpost.com/tables"
	status = 302

[[redirects]]
	from = "/staff_feedback"
	to = "https://ducompsoc.typeform.com/to/HGEsYJ"
	status = 302

[[redirects]]
	from = "/jointheteam"
	to = "https://ducompsoc.typeform.com/to/bzznhr"
	status = 302

[[redirects]]
	from ="/consentform"
	to = "/assets/consent_form.pdf"
	status = 302

[[redirects]]
	from ="/register"
	to = "https://ducompsoc.typeform.com/to/jGn1nbyC"
	status = 302

[[redirects]]
	from = "/tickets"
	to = "https://ducompsoc.typeform.com/to/jGn1nbyC"
	status = 302

[[redirects]]
	from = "/preregister"
	to = "/"
	status = 302

[[redirects]]
	from = "/toolbox"
	to = "https://drive.google.com/file/d/15yoLALjCbvCi0e_KDUK-Idz5EHzYCnam/view?usp=sharing"
	status = 302

[[redirects]]
	from = "/zoombackgrounds"
	to = "https://drive.google.com/drive/folders/19w-Smy4ZSAJs1iGWyvEJO2fP66FF482A?usp=sharing"
	status = 302

[dev]
	publish = "dist/"
