[[redirects]]
	from = "/codeofconduct"
	to = "/assets/dh18_code_of_conduct.pdf"
	status = 302

[[redirects]]
	from = "/sponsorshipdeck"
	to = "https://drive.google.com/file/d/1-XTLcm9eFmUsyVWDA9PQOrBvniFXPFmr/view"
	status = 302

[[redirects]]
	from = "/visaletter"
	to = "https://ducompsoc.typeform.com/to/Xr4WLQ"
	status = 302

[[redirects]]
	from = "/slack"
	to = "https://join.slack.com/t/durhack2019/shared_invite/enQtODI1NjIxODY3MDcyLWIwODFkYmU4ZmMxYzFhZGM3NzU5ZWFhZmYzYTcwM2E0YjIyYjhhNDFiYjNkZWJkYzg5YTE5ZDQwMTUxYWNhN2U"
	status = 302

[[redirects]]
	from = "/travel"
	to = "https://ducompsoc.typeform.com/to/Rjz1Js"
	status = 302

[[redirects]]
	from = "/devpost"
	to = "https://durhack2019.devpost.com"
	status = 302

[[redirects]]
	from = "/tables"
	to = "https://durhack2019.devpost.com/tables"
	status = 302
	
[[redirects]]
	from = "/staff_feedback"
	to = "https://ducompsoc.typeform.com/to/HGEsYJ"
	status = 302

[dev]
	publish = "dist/"
